export const articles = [
    {
        image: "/images/blogs/unsplash_Nv-vx3kUR2A.jpg",
        date: "February 18, 2025",
        title: "Top 4 Use Cases for an AI Phone Assistant in 2025 (DE)",
        readTime: "Now In 7 Min Read",
        imageAlt: "AI assistant with European Union stars",
    },
    {
        image: "/images/blogs/unsplash_Nv-vx3kUR2A-1.jpg",
        date: "February 18, 2025",
        title: "Automated lead qualification made easy: How the AI...",
        readTime: "Now In 7 Min Read",
        imageAlt: "Abstract shapes representing automated processes",
    },
    {
        image: "/images/blogs/unsplash_Nv-vx3kUR2A-2.jpg",
        date: "February 18, 2025",
        title: "AI call centers for businesses: A real opportunity or just hype?",
        readTime: "Now In 7 Min Read",
        imageAlt: "Person with a headset and AI icon",
    },
    {
        image: "/images/blogs/unsplash_Nv-vx3kUR2A-3.jpg",
        date: "February 18, 2025",
        title: "Top 11 AI Phone Assistants for German-Speaking Companies...",
        readTime: "Now In 7 Min Read",
        imageAlt: "Grid of various AI phone assistant logos",
    },
    {
        image: "/images/blogs/unsplash_Nv-vx3kUR2A-4.jpg",
        date: "February 18, 2025",
        title: "AI Phone - The perfect pilot project for your company in ...",
        readTime: "Now In 7 Min Read",
        imageAlt: "Person holding a phone with an AI chat on screen",
    },
    {
        image: "/images/blogs/unsplash_Nv-vx3kUR2A-5.jpg",
        date: "February 18, 2025",
        title: "fonio vs. fluently - The 2 AI phone assistants from Austria....",
        readTime: "Now In 7 Min Read",
        imageAlt: "Comparison of two different AI assistants",
    },
    {
        image: "/images/blogs/unsplash_Nv-vx3kUR2A-6.jpg",
        date: "February 18, 2025",
        title: "AI Phone Assistants: The 4 Best Use Cases for Businesses...",
        readTime: "Now In 7 Min Read",
        imageAlt: "Phone with AI application icons",
    },
    {
        image: "/images/blogs/unsplash_Nv-vx3kUR2A-7.jpg",
        date: "February 18, 2025",
        title: "Top 4 Use Cases for an AI Phone Assistant in 2025 (DE)",
        readTime: "Now In 7 Min Read",
        imageAlt: "AI assistants on a server",
    },
    {
        image: "/images/blogs/unsplash_Nv-vx3kUR2A-8.jpg",
        date: "February 18, 2025",
        title: "Top 4 Use Cases for an AI Phone Assistant in 2025 (DE)",
        readTime: "Now In 7 Min Read",
        imageAlt: "Cloud with a lock icon",
    },
    {
        image: "/images/blogs/unsplash_Nv-vx3kUR2A-9.jpg",
        date: "February 18, 2025",
        title: "Top 4 Use Cases for an AI Phone Assistant in 2025 (DE)",
        readTime: "Now In 7 Min Read",
        imageAlt: "Person using a laptop with a screen full of data",
    },
    {
        image: "/images/blogs/unsplash_Nv-vx3kUR2A-10.jpg",
        date: "February 18, 2025",
        title: "Top 4 Use Cases for an AI Phone Assistant in 2025 (DE)",
        readTime: "Now In 7 Min Read",
        imageAlt: 'Person in front of a box with "Fragile" written on it',
    },
    {
        image: "/images/blogs/unsplash_Nv-vx3kUR2A-11.jpg",
        date: "February 18, 2025",
        title: "Top 4 Use Cases for an AI Phone Assistant in 2025 (DE)",
        readTime: "Now In 7 Min Read",
        imageAlt: "Person building a block tower with other people",
    },
];